---
###########################################################
# Format shell scripts after changes are merged to main.  #
#                                                         #
# If shellfmt changes files, create/update the formatting #
# PR and auto-merge it.                                   #
###########################################################

name: Shell Format

on:
  pull_request:
    branches:
      - feat/shell-codeql-pipelines
    types:
      - opened
      - synchronize
      - reopened
    # paths:
    #   - ".shellcheckrc"
    #   - "linux/bash/**/*.sh"
    #   - "repo_scripts/**/*.sh"

  push:
    branches:
      - main
    paths:
      - "linux/bash/**/*.sh"
      - "repo_scripts/**/*.sh"

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  shell-quality:
    name: Shellfmt
    uses: redjax/PipelineTemplates/.github/workflows/shell-quality.yml@feat/shell-quality-checks
    with:
      pipelinetemplates-ref: feat/shell-quality-checks

      tools: shellfmt

      scan-path: "."

      ## Uncomment for dry-run mode
      shellfmt-mode: check
      shellfmt-commit-changes: false

      # shellfmt-mode: write
      # shellfmt-commit-changes: true
      shellfmt-commit-message: "chore(shell): format shell scripts"

      use-default-shellfmt-config: true

      fail-on-findings: false

      shellfmt-artifact-name: system-scripts-shellfmt-results
      artifact-retention-days: 30
